### ISSUE TITLE
Enum assignment to Vector3 panics with uninitialized arraystorage in versions 0.19 and 0.20

### ISSUE THREAD

**Issue by cprohoda** [dimforge/nalgebra#785] opened 2020-10-28 20:23 UTC
```
use nalgebra::Vector3;

#[derive(Debug, PartialEq, Copy, Clone)]
enum Blah {
    A,
    B,
    C,
}

fn main() {
    let test = Vector3::new(Blah::A, Blah::B, Blah::C);
    
    println!("{:?}", test)
}
```

The above code panics with `thread 'main' panicked at 'attempted to leave type nalgebra::ArrayStorage<Blah, nalgebra::U3, nalgebra::U1> uninitialized, which is invalid'` on nalgebra versions 0.19 and 0.20. It succeeds on versions 0.21, 0.22, and 0.23.

I've placed the minimum reproduction of the panic [in this repo](https://github.com/cprohoda/nalgebra_minimum_reproduction). Even though the issue is not present in the most recent versions of nalgebra, I'm reporting the error because the cause is unclear and I have not been able to find any other discussions on it

Edit - This bug appears to be limited to rustc nightly. For nalgebra 0.19, it failed on rustc 1.49.0-nightly but succeeded on rustc 1.47. Looks like it might be a nightly compiler bug

**Comment by sebcrozet** [comment] 2020-11-10 11:51
Hi! This was caused by nalgebra's former use of `std::mem::uninitialized`, which has been fixed in more recent versions of nalgebra. The assertion you are seeing is only enabled on the nightly compiler, which explains why it does not panic with the stable compiler.

Closing this because the problem is not present on the latest version of nalgebra.

**Closed by sebcrozet** 2020-11-10 11:51 UTC
