### ISSUE TITLE
Copy not implemented on types without `std` feature

### ISSUE THREAD

**Issue by vadixidav** [dimforge/nalgebra#774] opened 2020-10-13 01:56 UTC
In `nalgebra 0.22.0`, `IsometryMatrix3<f64>` no longer implements `Copy` only when the `std` feature is not present. When it is present, `Copy` is implemented. This has created a downstream issue in Rust CV `cv-core`.

Here is a minimal test case:

```toml
[dependencies]
nalgebra = { version = "0.22.0", default-features = false }
```

```rust
use nalgebra::IsometryMatrix3;

#[derive(Debug, Clone, Copy)]
struct A(pub IsometryMatrix3<f64>);

fn main() {}
```

**Comment by sebcrozet** [comment] 2020-10-13 08:08
In nalgebra 0.22.0, the use of `libm` when targeting `no-std` becomes opt-in. So enabling the `libm` feature of `nalgebra` is needed if you want to use `IsometryMatrix3` in any useful way (because without libm you won't have any trigonometric functions available).

That being said, I don't see any reasons why `IsometryMatrix3` would require `libm` to implement `Copy` itself. So we can consider this a regression that can be fixed by removing the `AbstractRotation` bound from the `Copy` trait implementation.

**Closed** 2020-10-13 08:27 UTC
Labels: P-high, bug
